
package com.mycompany.condominio_vistaverde;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class ConfiguraciónCuota extends javax.swing.JFrame {
    
  
    public ConfiguraciónCuota() {

    initComponents();


    txtCuotaActual1.setEditable(false);

    mostrarCuotaActual();
            this.setSize(900, 681);
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    }
    
private void mostrarCuotaActual() {

    String cuota = BDXML.obtenerCuotaActual();

    txtCuotaActual1.setText("Q. " + cuota);
}
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCuotaActual1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCuotaConfirmar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCuotaNueva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel6.setText("CONFIGURACIÓN CUOTA");

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setText("MENU");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton4)
                .addGap(145, 145, 145)
                .addComponent(jLabel6)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("NUEVA CUOTA:");

        txtCuotaActual1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("CUOTA ACTUAL:");

        txtCuotaConfirmar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtCuotaConfirmar.addActionListener(this::txtCuotaConfirmarActionPerformed);
        txtCuotaConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaConfirmarKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("CONFIRMAR CUOTA:");

        txtCuotaNueva.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtCuotaNueva.addActionListener(this::txtCuotaNuevaActionPerformed);
        txtCuotaNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaNuevaKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("CAMBIAR CUOTA");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCuotaActual1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(txtCuotaNueva)
                    .addComponent(txtCuotaConfirmar))
                .addGap(293, 319, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCuotaActual1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCuotaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCuotaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuotaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaNuevaActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaNuevaActionPerformed

    private void txtCuotaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaConfirmarActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String nuevaCuotaTexto = txtCuotaNueva.getText().trim();

String confirmarCuotaTexto =
        txtCuotaConfirmar.getText().trim();

if (nuevaCuotaTexto.isEmpty()
        || confirmarCuotaTexto.isEmpty()) {

    JOptionPane.showMessageDialog(this,
            "Debe completar todos los campos.");

    return;
}

double nuevaCuota;
double confirmarCuota;

try {

    nuevaCuota = Double.parseDouble(nuevaCuotaTexto);

    confirmarCuota =
            Double.parseDouble(confirmarCuotaTexto);

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Solo se permiten números y decimales.");

    return;
}

if (nuevaCuota <= 0 || confirmarCuota <= 0) {

    JOptionPane.showMessageDialog(this,
            "La cuota debe ser mayor a 0.");

    return;
}

if (nuevaCuota != confirmarCuota) {

    JOptionPane.showMessageDialog(this,
            "Las cuotas no coinciden.");

    return;
}

int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de actualizar la cuota?",
        "Confirmar actualización",
        JOptionPane.YES_NO_OPTION
);

if (respuesta != JOptionPane.YES_OPTION) {
    return;
}

BDXML.actualizarCuota(
        String.format("%.2f", nuevaCuota));

mostrarCuotaActual();

txtCuotaNueva.setText("");
txtCuotaConfirmar.setText("");

JOptionPane.showMessageDialog(this,
        "Cuota actualizada correctamente.");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCuotaNuevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaNuevaKeyTyped
validarEntradaDecimal(evt, txtCuotaNueva);           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaNuevaKeyTyped

    private void txtCuotaConfirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaConfirmarKeyTyped
validarEntradaDecimal(evt, txtCuotaNueva);           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaConfirmarKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCuotaActual1;
    private javax.swing.JTextField txtCuotaConfirmar;
    private javax.swing.JTextField txtCuotaNueva;
    // End of variables declaration//GEN-END:variables

    private void validarEntradaDecimal(java.awt.event.KeyEvent evt,
        javax.swing.JTextField campo) {

    char c = evt.getKeyChar();

    if (Character.isDigit(c)) {
        return;
    }

    if (c == '.') {

        if (campo.getText().contains(".")) {

            evt.consume();

            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números y decimales.");
        }

        return;
    }

    if (c == '\b') {
        return;
    }

    evt.consume();

    JOptionPane.showMessageDialog(this,
            "Solo se permiten números y decimales.");
}


    
}
