/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.condominio_vistaverde;
import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import org.w3c.dom.DOMException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class ConfiguraciónCuota extends javax.swing.JFrame {
    
  
    public ConfiguraciónCuota() {

    initComponents();

    cargarPagosEnTabla();

    txtCuotaActual1.setEditable(false);

    mostrarCuotaActual();
    }
    
private void mostrarCuotaActual() {

    String cuota = BDXML.obtenerCuotaActual();

    txtCuotaActual1.setText("Q. " + cuota);
}
    
    

    
private void cargarPagosEnTabla() {
 DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Casa");
    modelo.addColumn("Mes");
    modelo.addColumn("Año");
    modelo.addColumn("Cuota");

    try {

        Document doc = BDXML.obtenerDocumento();

        NodeList listaPagos = doc.getElementsByTagName("pago");

        for (int i = 0; i < listaPagos.getLength(); i++) {

            Element pago = (Element) listaPagos.item(i);

            String casa = pago.getElementsByTagName("casa")
                    .item(0).getTextContent();

            String mes = pago.getElementsByTagName("mes")
                    .item(0).getTextContent();

            String año = pago.getElementsByTagName("año")
                    .item(0).getTextContent();

            String cuota = pago.getElementsByTagName("cuota")
                    .item(0).getTextContent();

            modelo.addRow(new Object[]{
                casa,
                mes,
                año,
                "Q." + cuota
            });
        }

        TablaPagos.setModel(modelo);

    } catch (DOMException e) {

        JOptionPane.showMessageDialog(this,
                "Error al cargar pagos: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPagos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCuotaActual1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCuotaConfirmar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCuotaNueva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaPagos);

        jLabel1.setText("NUEVA CUOTA");

        jLabel2.setText("CUOTA ACTUAL");

        txtCuotaConfirmar.addActionListener(this::txtCuotaConfirmarActionPerformed);
        txtCuotaConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaConfirmarKeyTyped(evt);
            }
        });

        jLabel3.setText("CONFIRMAR CUOTA");

        txtCuotaNueva.addActionListener(this::txtCuotaNuevaActionPerformed);
        txtCuotaNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaNuevaKeyTyped(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(txtCuotaActual1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCuotaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCuotaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(265, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtCuotaActual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCuotaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCuotaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jLabel2)
                    .addContainerGap(176, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton2.setText("volvermenu");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnDelete.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnDelete)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) TablaPagos.getModel();
        int fila = TablaPagos.getSelectedRow();

if (fila < 0) {
    JOptionPane.showMessageDialog(this,
            "Debe seleccionar un pago de la tabla para eliminar.");
    return;
}

String casa = modelo.getValueAt(fila, 0).toString();
String mes = modelo.getValueAt(fila, 1).toString();
String anio = modelo.getValueAt(fila, 2).toString();

int respuesta = JOptionPane.showConfirmDialog(this,
        "¿Está seguro de eliminar el pago de:\n"
        + casa + " - " + mes + " - " + anio + "?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION);

if (respuesta == JOptionPane.YES_OPTION) {

    try {

        Document doc = BDXML.obtenerDocumento();

        NodeList listaPagos = doc.getElementsByTagName("pago");

        for (int i = 0; i < listaPagos.getLength(); i++) {

            Element pago = (Element) listaPagos.item(i);

            String casaXML = pago.getElementsByTagName("casa")
                    .item(0).getTextContent();

            String mesXML = pago.getElementsByTagName("mes")
                    .item(0).getTextContent();

            String anioXML = pago.getElementsByTagName("año")
                    .item(0).getTextContent();

            if (casaXML.equals(casa)
                    && mesXML.equals(mes)
                    && anioXML.equals(anio)) {

                // ELIMINA DEL XML
                pago.getParentNode().removeChild(pago);

                break;
            }
        }

        // GUARDA CAMBIOS EN XML
       BDXML.guardarDocumento(doc);

        // ELIMINA VISUALMENTE DE LA TABLA
        modelo.removeRow(fila);

        JOptionPane.showMessageDialog(this,
                "Pago eliminado correctamente.");

    } catch (HeadlessException | DOMException e) {

        JOptionPane.showMessageDialog(this,
                "Error al eliminar: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtCuotaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaNuevaActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaNuevaActionPerformed

    private void txtCuotaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaConfirmarActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String nuevaCuotaTexto = txtCuotaNueva.getText().trim();

String confirmarCuotaTexto =
        txtCuotaConfirmar.getText().trim();

if (nuevaCuotaTexto.isEmpty()
        || confirmarCuotaTexto.isEmpty()) {

    JOptionPane.showMessageDialog(this,
            "Debe completar todos los campos.");

    return;
}

double nuevaCuota;
double confirmarCuota;

try {

    nuevaCuota = Double.parseDouble(nuevaCuotaTexto);

    confirmarCuota =
            Double.parseDouble(confirmarCuotaTexto);

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(this,
            "Solo se permiten números y decimales.");

    return;
}

if (nuevaCuota <= 0 || confirmarCuota <= 0) {

    JOptionPane.showMessageDialog(this,
            "La cuota debe ser mayor a 0.");

    return;
}

if (nuevaCuota != confirmarCuota) {

    JOptionPane.showMessageDialog(this,
            "Las cuotas no coinciden.");

    return;
}

int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de actualizar la cuota?",
        "Confirmar actualización",
        JOptionPane.YES_NO_OPTION
);

if (respuesta != JOptionPane.YES_OPTION) {
    return;
}

BDXML.actualizarCuota(
        String.format("%.2f", nuevaCuota));

mostrarCuotaActual();

txtCuotaNueva.setText("");
txtCuotaConfirmar.setText("");

JOptionPane.showMessageDialog(this,
        "Cuota actualizada correctamente.");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCuotaNuevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaNuevaKeyTyped
validarEntradaDecimal(evt, txtCuotaNueva);           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaNuevaKeyTyped

    private void txtCuotaConfirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaConfirmarKeyTyped
validarEntradaDecimal(evt, txtCuotaNueva);           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaConfirmarKeyTyped

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPagos;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCuotaActual1;
    private javax.swing.JTextField txtCuotaConfirmar;
    private javax.swing.JTextField txtCuotaNueva;
    // End of variables declaration//GEN-END:variables

    private void validarEntradaDecimal(java.awt.event.KeyEvent evt,
        javax.swing.JTextField campo) {

    char c = evt.getKeyChar();

    if (Character.isDigit(c)) {
        return;
    }

    if (c == '.') {

        if (campo.getText().contains(".")) {

            evt.consume();

            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números y decimales.");
        }

        return;
    }

    if (c == '\b') {
        return;
    }

    evt.consume();

    JOptionPane.showMessageDialog(this,
            "Solo se permiten números y decimales.");
}


    
}
