/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.condominio_vistaverde;
import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import org.w3c.dom.DOMException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class ConfiguraciónCuota extends javax.swing.JFrame {
    
  
    public ConfiguraciónCuota() {

    initComponents();


    txtCuotaActual1.setEditable(false);

    mostrarCuotaActual();
            this.setSize(900, 681);
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    }
    
private void mostrarCuotaActual() {

    String cuota = BDXML.obtenerCuotaActual();

    txtCuotaActual1.setText("Q. " + cuota);
}
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCuotaActual1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCuotaConfirmar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCuotaNueva = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("NUEVA CUOTA:");

        txtCuotaActual1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("CUOTA ACTUAL:");

        txtCuotaConfirmar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txtCuotaConfirmar.addActionListener(this::txtCuotaConfirmarActionPerformed);
        txtCuotaConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaConfirmarKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("CONFIRMAR CUOTA:");

        txtCuotaNueva.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        txtCuotaNueva.addActionListener(this::txtCuotaNuevaActionPerformed);
        txtCuotaNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaNuevaKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setText("CAMBIAR CUOTA");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCuotaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuotaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuotaActual1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCuotaActual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCuotaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCuotaConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel4.setText("CONFIGURACIÓN CUOTA");

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("MENU");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuotaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaNuevaActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaNuevaActionPerformed

    private void txtCuotaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaConfirmarActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String nuevaCuotaTexto = txtCuotaNueva.getText().trim();
String confirmarCuotaTexto = txtCuotaConfirmar.getText().trim();

// 1. Validación de campos vacíos
if (nuevaCuotaTexto.isEmpty() || confirmarCuotaTexto.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
    return;
}

double nuevaCuota;
double confirmarCuota;

try {
    // Reemplazamos coma por punto por si el usuario usa el teclado numérico con configuración regional distinta
    nuevaCuota = Double.parseDouble(nuevaCuotaTexto.replace(",", "."));
    confirmarCuota = Double.parseDouble(confirmarCuotaTexto.replace(",", "."));

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Solo se permiten números y decimales (use punto para decimal).");
    return;
}

// 2. Validación de valores lógicos
if (nuevaCuota <= 0 || confirmarCuota <= 0) {
    JOptionPane.showMessageDialog(this, "La cuota debe ser mayor a 0.");
    return;
}

// 3. Comparación exacta
if (Double.compare(nuevaCuota, confirmarCuota) != 0) {
    JOptionPane.showMessageDialog(this, "Las cuotas no coinciden.");
    return;
}

// 4. Diálogo con botones en español (Sí / No)
Object[] opciones = {"Sí", "No"};
int respuesta = JOptionPane.showOptionDialog(
        this,
        "¿Está seguro de actualizar la cuota a: Q." + String.format("%.2f", nuevaCuota) + "?",
        "Confirmar actualización",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        opciones,
        opciones[0]
);

if (respuesta != JOptionPane.YES_OPTION) {
    return;
}

// 5. Guardado (Usamos el punto decimal para la BD)
BDXML.actualizarCuota(String.format(java.util.Locale.US, "%.2f", nuevaCuota));

mostrarCuotaActual();
txtCuotaNueva.setText("");
txtCuotaConfirmar.setText("");

JOptionPane.showMessageDialog(this, "Cuota actualizada correctamente.");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCuotaNuevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaNuevaKeyTyped
validarEntradaDecimal(evt, txtCuotaNueva);           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaNuevaKeyTyped

    private void txtCuotaConfirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaConfirmarKeyTyped
validarEntradaDecimal(evt, txtCuotaConfirmar);           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaConfirmarKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCuotaActual1;
    private javax.swing.JTextField txtCuotaConfirmar;
    private javax.swing.JTextField txtCuotaNueva;
    // End of variables declaration//GEN-END:variables

    private void validarEntradaDecimal(java.awt.event.KeyEvent evt,
        javax.swing.JTextField campo) {

    char c = evt.getKeyChar();

    if (Character.isDigit(c)) {
        return;
    }

    if (c == '.') {

        if (campo.getText().contains(".")) {

            evt.consume();

            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números y decimales.");
        }

        return;
    }

    if (c == '\b') {
        return;
    }

    evt.consume();

    JOptionPane.showMessageDialog(this,
            "Solo se permiten números y decimales.");
}


    
}
