/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.condominio_vistaverde;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class RegistroCuotaPago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroCuotaPago.class.getName());

    /**
     * Creates new form RegistroCuotaPago
     */
    public RegistroCuotaPago() {

    initComponents();

    txtCuota.setEditable(false);

txtCuota.setText(
        "Q." + BDXML.obtenerCuotaActual());
    CargarCasas();
    CargarMeses();
    CargarAños();

    btnPago.setEnabled(false);
            this.setSize(900, 681);
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    }
    
   private void CargarCasas() {

    DefaultComboBoxModel<String> modelo =
            new DefaultComboBoxModel<>();

    modelo.addElement("Seleccionar");

    for (int i = 1; i <= 30; i++) {
        modelo.addElement("CASA " + i);
    }

    cmbCasas.setModel(modelo);
}
    
     private void CargarMeses() {

    cmbMes.removeAllItems();

    cmbMes.addItem("Seleccionar");

    cmbMes.addItem("Enero");
    cmbMes.addItem("Febrero");
    cmbMes.addItem("Marzo");
    cmbMes.addItem("Abril");
    cmbMes.addItem("Mayo");
    cmbMes.addItem("Junio");
    cmbMes.addItem("Julio");
    cmbMes.addItem("Agosto");
    cmbMes.addItem("Septiembre");
    cmbMes.addItem("Octubre");
    cmbMes.addItem("Noviembre");
    cmbMes.addItem("Diciembre");
}
    
    private void CargarAños() {
    cmbAño.removeAllItems();
cmbAño.addItem("Seleccionar");
   cmbAño.addItem("2026");
    cmbAño.addItem("2027");
    cmbAño.addItem("2028");
}
    
    // Arreglo para conocer el orden lógico de los meses
    private final String[] ORDEN_MESES = {
        "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
    };

    /**
     * Revisa si todos los meses anteriores al mes seleccionado ya fueron pagados.
     * Retorna el nombre del primer mes que falta por pagar, o null si todo está correcto.
     */
    private String obtenerMesAnteriorNoPagado(String casa, String mesSeleccionado, String anio) {
        for (String mes : ORDEN_MESES) {
            // Si el ciclo llega al mes que queremos pagar, significa que los anteriores están pagados
            if (mes.equals(mesSeleccionado)) {
                break; 
            }
            
            // Verificamos si el mes anterior iterado NO existe en el XML
            if (!BDXML.existePago(casa, mes, anio)) {
                return mes; // Retornamos el mes que falta pagar
            }
        }
        return null; // Si termina el ciclo o llega al break, todo está en orden
    }
    
    
    
    
    private void validarCombos() {
 if (cmbCasas.getSelectedItem() == null
            || cmbMes.getSelectedItem() == null
            || cmbAño.getSelectedItem() == null) {

        btnPago.setEnabled(false);
        return;
    }

    String casa = cmbCasas.getSelectedItem().toString();
    String mes = cmbMes.getSelectedItem().toString();
    String anio = cmbAño.getSelectedItem().toString();

    boolean habilitar =
            !casa.equals("Seleccionar")
            && !mes.equals("Seleccionar")
            && !anio.equals("Seleccionar");

    btnPago.setEnabled(habilitar);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPago = new javax.swing.JButton();
        txtCuota = new javax.swing.JTextField();
        cmbCasas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("CASA");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("MES");

        cmbMes.setBackground(new java.awt.Color(0, 51, 51));
        cmbMes.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMes.addActionListener(this::cmbMesActionPerformed);

        cmbAño.setBackground(new java.awt.Color(0, 51, 51));
        cmbAño.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAño.addActionListener(this::cmbAñoActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("AÑO");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("CUOTA");

        btnPago.setBackground(new java.awt.Color(0, 0, 51));
        btnPago.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnPago.setText("APLICAR PAGO");
        btnPago.addActionListener(this::btnPagoActionPerformed);

        txtCuota.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N

        cmbCasas.setBackground(new java.awt.Color(0, 51, 51));
        cmbCasas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        cmbCasas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCasas.addActionListener(this::cmbCasasActionPerformed);

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCasas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnPago))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPago, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel5.setText("REGISTRO CUOTA PAGO");

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("MENU");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
// --- COMIENZO DEL CÓDIGO DEL BOTÓN ---
String casa = cmbCasas.getSelectedItem().toString();
String mes = cmbMes.getSelectedItem().toString();
String año = cmbAño.getSelectedItem().toString();

// 1. NUEVA VALIDACIÓN: BUSCAR DUEÑO EN EL XML
String[] datosDueño = BDXML.obtenerDatosPropietario(casa);

if (datosDueño == null) {
    JOptionPane.showMessageDialog(this, 
        "ERROR: No hay ningún dueño registrado para la " + casa + ".\n" +
        "Debe registrar al propietario antes de recibir pagos.", 
        "Sin Propietario", JOptionPane.ERROR_MESSAGE);
    return;
}

String nombrePropietario = datosDueño[0];
String correoDestino = datosDueño[1];

// OBTENER CUOTA ACTUAL DEL XML
String cuota = BDXML.obtenerCuotaActual();

// --- VALIDACIÓN CRONOLÓGICA (Tu código actual) ---
String mesFaltante = obtenerMesAnteriorNoPagado(casa, mes, año);
if (mesFaltante != null) {
    JOptionPane.showMessageDialog(this,
            "No se permite registrar el mes de " + mes + ".\n"
            + "Falta registrar el pago del mes de: " + mesFaltante + " del año " + año,
            "Pago correlativo requerido",
            JOptionPane.WARNING_MESSAGE);
    return; 
}

// --- VALIDAR DUPLICADOS (Tu código actual) ---
if (BDXML.existePago(casa, mes, año)) {
    JOptionPane.showMessageDialog(this,
            "Ya existe un pago registrado para " + casa + " en " + mes + " del año " + año);
    return;
}

// CONFIRMACIÓN CON NOMBRE DEL DUEÑO
Object[] opciones = {"Sí", "No"};
int respuesta = JOptionPane.showOptionDialog(
        this,
        "¿Está seguro de registrar el pago?\n\n"
        + "Propietario: " + nombrePropietario + "\n" // Ahora muestra el nombre
        + "Casa: " + casa + "\n"
        + "Mes: " + mes + "\n"
        + "Año: " + año + "\n"
        + "Cuota: Q." + cuota,
        "Confirmar pago",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null, opciones, opciones[0]
);

if (respuesta != JOptionPane.YES_OPTION) {
    return;
}

// REGISTRO Y ENVÍO
BDXML.registrarPago(casa, mes, año, cuota);

// Modificamos la llamada para pasarle el correo y el nombre extraídos
enviarCorreoPago(casa, mes, año, cuota, correoDestino, nombrePropietario);

JOptionPane.showMessageDialog(this, "Pago registrado correctamente y recibo enviado a: " + correoDestino);

// RESET (Tu código actual)
cmbCasas.setSelectedIndex(0);
cmbMes.setSelectedIndex(0);
cmbAño.setSelectedIndex(0);
txtCuota.setText("Q. " + cuota);
btnPago.setEnabled(false);
    }//GEN-LAST:event_btnPagoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCasasActionPerformed
        validarCombos();
    // TODO add your handling code here:
    }//GEN-LAST:event_cmbCasasActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
  validarCombos();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
    validarCombos();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAñoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
VisualizarDatos VD = new VisualizarDatos ();
        VD.setVisible(true);
        dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroCuotaPago().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPago;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbCasas;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCuota;
    // End of variables declaration//GEN-END:variables

private void enviarCorreoPago(String casa, String mes, String año, String cuota, String destino, String nombreDuenio) {
    new Thread(() -> {
        final String remitente = "2021-50077@liceocanadiense.edu.gt"; // Tu correo de remitente
        final String clave = "zofh xszd czvt ucrj";    // Tu App Password de Google

        java.util.Properties props = new java.util.Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");

        jakarta.mail.Session session = jakarta.mail.Session.getInstance(props, new jakarta.mail.Authenticator() {
            @Override
            protected jakarta.mail.PasswordAuthentication getPasswordAuthentication() {
                return new jakarta.mail.PasswordAuthentication(remitente, clave);
            }
        });

        try {
            jakarta.mail.Message message = new jakarta.mail.internet.MimeMessage(session);
            message.setFrom(new jakarta.mail.internet.InternetAddress(remitente));
            
            // Ahora usamos la variable 'destino' que viene del XML
            message.setRecipients(jakarta.mail.Message.RecipientType.TO, 
                    jakarta.mail.internet.InternetAddress.parse(destino));
            
            message.setSubject("RECIBO DE PAGO: " + mes + " " + año + " - Casa " + casa);
            
            // Diseño HTML mejorado con el nombre del propietario
            String html = "<div style='font-family: Arial, sans-serif; border: 2px solid #000033; padding: 25px; width: 350px; border-radius: 10px;'>"
                        + "<h2 style='color: #000033; text-align: center; margin-top: 0;'>VISTA VERDE</h2>"
                        + "<div style='background-color: #f0f0f0; padding: 10px; border-radius: 5px;'>"
                        + "<p style='margin: 5px 0;'><b>Propietario:</b> " + nombreDuenio + "</p>"
                        + "<p style='margin: 5px 0;'><b>Casa No.:</b> " + casa + "</p>"
                        + "</div>"
                        + "<hr style='border: 1px dashed #ccc; margin: 15px 0;'>"
                        + "<p style='margin: 5px 0;'><b>Concepto:</b> Mantenimiento Mensual</p>"
                        + "<p style='margin: 5px 0;'><b>Periodo:</b> " + mes + " " + año + "</p>"
                        + "<h3 style='color: #28a745; margin: 15px 0;'>Monto Pagado: Q." + cuota + "</h3>"
                        + "<hr style='border: 1px solid #000033;'>"
                        + "<p style='font-size: 0.85em; color: #555; text-align: center;'>Este es un comprobante oficial de pago generado automáticamente.</p>"
                        + "</div>";
            
            message.setContent(html, "text/html; charset=utf-8");

            jakarta.mail.Transport.send(message);
            System.out.println("Correo enviado exitosamente a: " + destino);
            
        } catch (Exception e) {
            System.err.println("Error al enviar el correo: " + e.getMessage());
            e.printStackTrace();
        }
    }).start();
}}
