package com.mycompany.condominio_vistaverde;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue
 */
public class RegistroPropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroPropietario.class.getName());

    /**
     * Creates new form REGISTRO_PROPIETARIO
     */
    public RegistroPropietario() {
        initComponents();
        this.setSize(900, 681);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarCasas();
        this.setSize(900, 681);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    private void cargarCasas() {
    nocasas.removeAllItems();
    nocasas.addItem("Seleccione una casa");

    for (int i = 1; i <= 30; i++) {
        nocasas.addItem(String.valueOf(i));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombrecom = new javax.swing.JTextField();
        nocasas = new javax.swing.JComboBox<>();
        cellphone = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Volver a Menu");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE PROPIETARIO");

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Numero de Casa:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Correo Electronico:");

        nombrecom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrecomKeyTyped(evt);
            }
        });

        nocasas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nocasas.addActionListener(this::nocasasActionPerformed);

        cellphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cellphoneKeyTyped(evt);
            }
        });

        correo.addActionListener(this::correoActionPerformed);

        jButton1.setText("Guardar Propietario");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Limpiar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrecom)
                                    .addComponent(nocasas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cellphone)
                                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(277, 277, 277))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nombrecom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nocasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void nocasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocasasActionPerformed
        
    }//GEN-LAST:event_nocasasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nombre = nombrecom.getText().trim();
    String casa = nocasas.getSelectedItem().toString();
    String tel = cellphone.getText().trim();
    String mail = correo.getText().trim();

    if (nombre.isEmpty() || tel.isEmpty() || mail.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        return;
    }

    new Thread(() -> {
        try {
            // 1. Primero intentamos registrar en XML (Esto valida si la casa está libre)
            BDXML.registrarPropietario(casa, nombre, tel, mail);
            
            // 2. Si el registro XML fue exitoso, enviamos el correo
            enviarCorreoVerificacion(mail, nombre);
            
            javax.swing.SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, "Registro exitoso. Se ha enviado un correo a " + mail);
                limpiarCampos();
            });
            
        } catch (Exception e) {
            // Aquí atrapamos tanto el error de "Casa ocupada" como el de "Correo inválido"
            javax.swing.SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Registro", JOptionPane.ERROR_MESSAGE);
            });
        }
    }).start();
}

// Método de apoyo para limpiar
private void limpiarCampos() {
    nombrecom.setText("");
    cellphone.setText("");
    correo.setText("");
    nocasas.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cellphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellphoneKeyTyped
  char c = evt.getKeyChar();

    if(!Character.isDigit(c)){

        evt.consume();

    }        // TODO add your handling code here:
    }//GEN-LAST:event_cellphoneKeyTyped

    private void nombrecomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrecomKeyTyped
 char c = evt.getKeyChar();

    if(Character.isDigit(c)){

        evt.consume();

    }        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecomKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroPropietario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cellphone;
    private javax.swing.JTextField correo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> nocasas;
    private javax.swing.JTextField nombrecom;
    // End of variables declaration//GEN-END:variables

public boolean validarCorreo(String correo){

    String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

    return correo.matches(regex);
}

private void enviarCorreoVerificacion(String destino, String nombre) {
    
    final String remitente = "2021-50077@liceocanadiense.edu.gt";
    final String clave = "zofh xszd czvt ucrj";

    java.util.Properties props = new java.util.Properties();
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");
    props.put("mail.smtp.ssl.trust", "smtp.gmail.com");

    jakarta.mail.Session session = jakarta.mail.Session.getInstance(props,
        new jakarta.mail.Authenticator() {
            @Override
            protected jakarta.mail.PasswordAuthentication getPasswordAuthentication() {
                return new jakarta.mail.PasswordAuthentication(remitente, clave);
            }
        });

    try {

        jakarta.mail.Message message = new jakarta.mail.internet.MimeMessage(session);

        message.setFrom(new jakarta.mail.internet.InternetAddress(remitente));

        message.setRecipients(
                jakarta.mail.Message.RecipientType.TO,
                jakarta.mail.internet.InternetAddress.parse(destino)
        );

        message.setSubject("VERIFICACIÓN DE CUENTA - VISTA VERDE");

        // Diseño HTML bonito
        String html =
                "<div style='font-family: Arial, sans-serif; "
                + "max-width: 500px; "
                + "margin: auto; "
                + "border: 2px solid #000033; "
                + "border-radius: 12px; "
                + "overflow: hidden;'>"

                // Encabezado
                + "<div style='background-color: #000033; "
                + "color: white; "
                + "padding: 20px; "
                + "text-align: center;'>"

                + "<h1 style='margin:0;'>VISTA VERDE</h1>"
                + "<p style='margin:5px 0;'>Sistema de Gestión Residencial</p>"
                + "</div>"

                // Contenido
                + "<div style='padding: 25px;'>"

                + "<h2 style='color:#000033;'>¡Bienvenido/a!</h2>"

                + "<p>Hola <b>" + nombre + "</b>,</p>"

                + "<p>Tu cuenta ha sido registrada exitosamente en el sistema "
                + "del Condominio Vista Verde.</p>"

                + "<div style='background:#f4f4f4; "
                + "padding:15px; "
                + "border-radius:8px; "
                + "margin:20px 0;'>"

                + "<p style='margin:5px 0;'><b>Correo registrado:</b> "
                + destino + "</p>"

                + "<p style='margin:5px 0;'><b>Estado:</b> Cuenta verificada correctamente</p>"

                + "</div>"

                + "<p>Ahora podrás recibir notificaciones importantes sobre:</p>"

                + "<ul>"
                + "<li>Pagos realizados</li>"
                + "<li>Avisos administrativos</li>"
                + "<li>Información del condominio</li>"
                + "</ul>"

                + "<hr>"

                + "<p style='font-size: 12px; color: gray; text-align:center;'>"
                + "Este es un correo automático generado por el sistema Vista Verde."
                + "</p>"

                + "</div>"
                + "</div>";

        message.setContent(html, "text/html; charset=utf-8");

        jakarta.mail.Transport.send(message);

        System.out.println("Correo de verificación enviado.");

    } catch (Exception e) {
        e.printStackTrace();
        throw new RuntimeException("Error al enviar correo: " + e.getMessage());
    }
}
}
