/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.condominio_vistaverde;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class RegistroCuotaPago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroCuotaPago.class.getName());

    /**
     * Creates new form RegistroCuotaPago
     */
    public RegistroCuotaPago() {

    initComponents();

    txtCuota.setEditable(false);

txtCuota.setText(
        "Q." + BDXML.obtenerCuotaActual());
    CargarCasas();
    CargarMeses();
    CargarAños();

    btnPago.setEnabled(false);
    }
    
   private void CargarCasas() {

    DefaultComboBoxModel<String> modelo =
            new DefaultComboBoxModel<>();

    modelo.addElement("Seleccionar");

    for (int i = 1; i <= 30; i++) {
        modelo.addElement("CASA " + i);
    }

    cmbCasas.setModel(modelo);
}
    
     private void CargarMeses() {

    cmbMes.removeAllItems();

    cmbMes.addItem("Seleccionar");

    cmbMes.addItem("Enero");
    cmbMes.addItem("Febrero");
    cmbMes.addItem("Marzo");
    cmbMes.addItem("Abril");
    cmbMes.addItem("Mayo");
    cmbMes.addItem("Junio");
    cmbMes.addItem("Julio");
    cmbMes.addItem("Agosto");
    cmbMes.addItem("Septiembre");
    cmbMes.addItem("Octubre");
    cmbMes.addItem("Noviembre");
    cmbMes.addItem("Diciembre");
}
    
    private void CargarAños() {
    cmbAño.removeAllItems();
cmbAño.addItem("Seleccionar");
   cmbAño.addItem("2026");
    cmbAño.addItem("2027");
    cmbAño.addItem("2028");
}
    
    // Arreglo para conocer el orden lógico de los meses
    private final String[] ORDEN_MESES = {
        "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
    };

    /**
     * Revisa si todos los meses anteriores al mes seleccionado ya fueron pagados.
     * Retorna el nombre del primer mes que falta por pagar, o null si todo está correcto.
     */
    private String obtenerMesAnteriorNoPagado(String casa, String mesSeleccionado, String anio) {
        for (String mes : ORDEN_MESES) {
            // Si el ciclo llega al mes que queremos pagar, significa que los anteriores están pagados
            if (mes.equals(mesSeleccionado)) {
                break; 
            }
            
            // Verificamos si el mes anterior iterado NO existe en el XML
            if (!BDXML.existePago(casa, mes, anio)) {
                return mes; // Retornamos el mes que falta pagar
            }
        }
        return null; // Si termina el ciclo o llega al break, todo está en orden
    }
    
    
    
    
    private void validarCombos() {
 if (cmbCasas.getSelectedItem() == null
            || cmbMes.getSelectedItem() == null
            || cmbAño.getSelectedItem() == null) {

        btnPago.setEnabled(false);
        return;
    }

    String casa = cmbCasas.getSelectedItem().toString();
    String mes = cmbMes.getSelectedItem().toString();
    String anio = cmbAño.getSelectedItem().toString();

    boolean habilitar =
            !casa.equals("Seleccionar")
            && !mes.equals("Seleccionar")
            && !anio.equals("Seleccionar");

    btnPago.setEnabled(habilitar);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        cmbAño = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPago = new javax.swing.JButton();
        txtCuota = new javax.swing.JTextField();
        cmbCasas = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CASA");

        jLabel2.setText("MES");

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMes.addActionListener(this::cmbMesActionPerformed);

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAño.addActionListener(this::cmbAñoActionPerformed);

        jLabel3.setText("AÑO");

        jLabel4.setText("CUOTA");

        btnPago.setText("Aplicar Pago");
        btnPago.addActionListener(this::btnPagoActionPerformed);

        cmbCasas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCasas.addActionListener(this::cmbCasasActionPerformed);

        jButton2.setText("volvermenu");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
String casa = cmbCasas.getSelectedItem().toString();
        String mes = cmbMes.getSelectedItem().toString();
        String año = cmbAño.getSelectedItem().toString();

        // OBTENER CUOTA ACTUAL DEL XML
        String cuota = BDXML.obtenerCuotaActual();

        // --------------------------------------------------------
        // NUEVA VALIDACIÓN: ORDEN CRONOLÓGICO DE PAGOS
        // --------------------------------------------------------
        String mesFaltante = obtenerMesAnteriorNoPagado(casa, mes, año);
        
        if (mesFaltante != null) {
            JOptionPane.showMessageDialog(this,
                    "No se permite registrar el mes de " + mes + ".\n"
                    + "Falta registrar el pago del mes de: " + mesFaltante + " del año " + año,
                    "Pago correlativo requerido",
                    JOptionPane.WARNING_MESSAGE);
            return; // Detenemos la ejecución para que no proceda al pago
        }
        // --------------------------------------------------------

        // VALIDAR DUPLICADOS
        if (BDXML.existePago(casa, mes, año)) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe un pago registrado para "
                    + casa + " en "
                    + mes + " del año "
                    + año
                    + ".\nNo se puede duplicar el pago.");
            return;
        }

        // CONFIRMACIÓN
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de registrar el pago?\n\n"
                + "Casa: " + casa
                + "\nMes: " + mes
                + "\nAño: " + año
                + "\nCuota: Q." + cuota,
                "Confirmar pago",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        // GUARDAR PAGO
        BDXML.registrarPago(casa, mes, año, cuota);

        JOptionPane.showMessageDialog(this, "Pago registrado correctamente.");

        // RESET
        cmbCasas.setSelectedIndex(0);
        cmbMes.setSelectedIndex(0);
        cmbAño.setSelectedIndex(0);
        txtCuota.setText("Q. " + cuota);
        btnPago.setEnabled(false);
    }//GEN-LAST:event_btnPagoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCasasActionPerformed
        validarCombos();
    // TODO add your handling code here:
    }//GEN-LAST:event_cmbCasasActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
  validarCombos();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
    validarCombos();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroCuotaPago().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPago;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbCasas;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCuota;
    // End of variables declaration//GEN-END:variables
}
